import { CreateRequestBuilder, DeleteRequestBuilder, GetAllRequestBuilder, GetByKeyRequestBuilder, ODataBatchChangeSet, ODataBatchRequestBuilder, UpdateRequestBuilder } from '@sap-cloud-sdk/core';
import { AlmacenesSet, NombreCuentaSet, PropuestaPagoSet, CaracteriticasSet, Almacenes001Set, CaracteriticasV2Set, SociedadSet, CentrosSet, SegmentosSet, TipoCambioSet, UpdtVinMatriculaSet, Segmentos001Set, ModenasAppSet, FdHdSet, FdItemsSet, PaiseSet } from './index';
/**
 * Batch builder for operations supported on the Z Od Scp Core 0001 Service.
 * @param requests The requests of the batch
 * @returns A request builder for batch.
 */
export declare function batch(...requests: Array<ReadZOdScpCore0001ServiceRequestBuilder | ODataBatchChangeSet<WriteZOdScpCore0001ServiceRequestBuilder>>): ODataBatchRequestBuilder;
/**
 * Change set constructor consists of write operations supported on the Z Od Scp Core 0001 Service.
 * @param requests The requests of the change set
 * @returns A change set for batch.
 */
export declare function changeset(...requests: WriteZOdScpCore0001ServiceRequestBuilder[]): ODataBatchChangeSet<WriteZOdScpCore0001ServiceRequestBuilder>;
export declare const defaultZOdScpCore0001ServicePath = "/sap/opu/odata/sap/Z_OD_SCP_CORE_0001_SRV";
export declare type ReadZOdScpCore0001ServiceRequestBuilder = GetAllRequestBuilder<AlmacenesSet> | GetAllRequestBuilder<NombreCuentaSet> | GetAllRequestBuilder<PropuestaPagoSet> | GetAllRequestBuilder<CaracteriticasSet> | GetAllRequestBuilder<Almacenes001Set> | GetAllRequestBuilder<CaracteriticasV2Set> | GetAllRequestBuilder<SociedadSet> | GetAllRequestBuilder<CentrosSet> | GetAllRequestBuilder<SegmentosSet> | GetAllRequestBuilder<TipoCambioSet> | GetAllRequestBuilder<UpdtVinMatriculaSet> | GetAllRequestBuilder<Segmentos001Set> | GetAllRequestBuilder<ModenasAppSet> | GetAllRequestBuilder<FdHdSet> | GetAllRequestBuilder<FdItemsSet> | GetAllRequestBuilder<PaiseSet> | GetByKeyRequestBuilder<AlmacenesSet> | GetByKeyRequestBuilder<NombreCuentaSet> | GetByKeyRequestBuilder<PropuestaPagoSet> | GetByKeyRequestBuilder<CaracteriticasSet> | GetByKeyRequestBuilder<Almacenes001Set> | GetByKeyRequestBuilder<CaracteriticasV2Set> | GetByKeyRequestBuilder<SociedadSet> | GetByKeyRequestBuilder<CentrosSet> | GetByKeyRequestBuilder<SegmentosSet> | GetByKeyRequestBuilder<TipoCambioSet> | GetByKeyRequestBuilder<UpdtVinMatriculaSet> | GetByKeyRequestBuilder<Segmentos001Set> | GetByKeyRequestBuilder<ModenasAppSet> | GetByKeyRequestBuilder<FdHdSet> | GetByKeyRequestBuilder<FdItemsSet> | GetByKeyRequestBuilder<PaiseSet>;
export declare type WriteZOdScpCore0001ServiceRequestBuilder = CreateRequestBuilder<AlmacenesSet> | UpdateRequestBuilder<AlmacenesSet> | DeleteRequestBuilder<AlmacenesSet> | CreateRequestBuilder<NombreCuentaSet> | UpdateRequestBuilder<NombreCuentaSet> | DeleteRequestBuilder<NombreCuentaSet> | CreateRequestBuilder<PropuestaPagoSet> | UpdateRequestBuilder<PropuestaPagoSet> | DeleteRequestBuilder<PropuestaPagoSet> | CreateRequestBuilder<CaracteriticasSet> | UpdateRequestBuilder<CaracteriticasSet> | DeleteRequestBuilder<CaracteriticasSet> | CreateRequestBuilder<Almacenes001Set> | UpdateRequestBuilder<Almacenes001Set> | DeleteRequestBuilder<Almacenes001Set> | CreateRequestBuilder<CaracteriticasV2Set> | UpdateRequestBuilder<CaracteriticasV2Set> | DeleteRequestBuilder<CaracteriticasV2Set> | CreateRequestBuilder<SociedadSet> | UpdateRequestBuilder<SociedadSet> | DeleteRequestBuilder<SociedadSet> | CreateRequestBuilder<CentrosSet> | UpdateRequestBuilder<CentrosSet> | DeleteRequestBuilder<CentrosSet> | CreateRequestBuilder<SegmentosSet> | UpdateRequestBuilder<SegmentosSet> | DeleteRequestBuilder<SegmentosSet> | CreateRequestBuilder<TipoCambioSet> | UpdateRequestBuilder<TipoCambioSet> | DeleteRequestBuilder<TipoCambioSet> | CreateRequestBuilder<UpdtVinMatriculaSet> | UpdateRequestBuilder<UpdtVinMatriculaSet> | DeleteRequestBuilder<UpdtVinMatriculaSet> | CreateRequestBuilder<Segmentos001Set> | UpdateRequestBuilder<Segmentos001Set> | DeleteRequestBuilder<Segmentos001Set> | CreateRequestBuilder<ModenasAppSet> | UpdateRequestBuilder<ModenasAppSet> | DeleteRequestBuilder<ModenasAppSet> | CreateRequestBuilder<FdHdSet> | UpdateRequestBuilder<FdHdSet> | DeleteRequestBuilder<FdHdSet> | CreateRequestBuilder<FdItemsSet> | UpdateRequestBuilder<FdItemsSet> | DeleteRequestBuilder<FdItemsSet> | CreateRequestBuilder<PaiseSet> | UpdateRequestBuilder<PaiseSet> | DeleteRequestBuilder<PaiseSet>;
//# sourceMappingURL=BatchRequest.d.ts.map